In [2]:
import numpy as np
np.__version__

!pip install --upgrade numpy # it was on v1.25 so I had to update it

# Import the upgraded version of NumPy and print the version again - do this after restarting the kernel
import numpy as np
print(np.__version__)

'2.1.1'

In [5]:
# importar biblioteca e inspecionar versão
!pip install pandas
import pandas as pd
pd.__version__

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 4.7 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 356.4 kB/s eta 0:00:000:00:01m eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 2.5 MB/s eta 0:00:00m eta 0:00:010:00:01


'2.2.2'

### Exercício-001
Crie uma matriz 3x3 com valores variando de 0 a 8:

In [6]:
import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Exercício-002
Adicione uma borda ao redor de uma matriz numpy. Utilize _fancy indexing_.

In [11]:
import numpy as np

# Create a 3x3 matrix with values ranging from 0 to 8
original_matrix = np.arange(9).reshape(3, 3)
print("Original matrix:", original_matrix)

# Create a larger 5x5 matrix filled with the border value (e.g., 0)
border_value = 0
bordered_matrix = np.full((5, 5), border_value)
print("Bordered matrix:", bordered_matrix)

Original matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]
Bordered matrix: [[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [12]:
# Use fancy indexing to place the original matrix in the center of the bordered matrix
bordered_matrix[1:-1, 1:-1] = original_matrix

print("Original 3x3 Matrix:")
print("Original matrix:", original_matrix)

print("\n5x5 Matrix with Border Added:")
print("Bordered matrix:", bordered_matrix)

Original 3x3 Matrix:
Original matrix: [[0 1 2]
 [3 4 5]
 [6 7 8]]

5x5 Matrix with Border Added:
Bordered matrix: [[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


### Exercício-003
Mude a escala uma matriz numpy de dimensões 5x5 com a seguinte formulação:

$z=\frac{x_i-\bar{x}}{std(x)}$

In [13]:
import numpy as np

# Criando uma matriz 5x5 com valores aleatórios
np.random.seed(1234)  # reprodutibilidade
matrix = np.random.randint(1, 100, size=(5, 5))

# Calculando a média e o desvio padrão da matriz
mean_value = np.mean(matrix)
std_value = np.std(matrix)

print("Média:", mean_value)
print("Desvio padrão:", std_value)

Média: 49.68
Desvio padrão: 21.342389744356183


In [14]:
# Aplicando a formulação para mudar a escala
scaled_matrix = (matrix - mean_value) / std_value

print("Matriz original:")
print(matrix)

print("\nMatriz escalada:")
print(scaled_matrix)

Matriz original:
[[48 84 39 54 77]
 [25 16 50 24 27]
 [31 44 31 27 59]
 [93 70 81 74 48]
 [51 77 38 35 39]]

Matriz escalada:
[[-0.07871658  1.60806734 -0.50041257  0.20241407  1.28008158]
 [-1.15638409 -1.57808007  0.01499363 -1.2032392  -1.06267387]
 [-0.87525344 -0.26613702 -0.87525344 -1.06267387  0.43668962]
 [ 2.02976333  0.95209582  1.46750202  1.13951625 -0.07871658]
 [ 0.06184874  1.28008158 -0.54726767 -0.687833   -0.50041257]]


### Exercício-004
Crie um `array` numpy aleatório com 10 elementos e ordene utilizando um método da biblioteca numpy.


In [17]:
import numpy as np

# Cria um array numpy com 10 elementos aleatórios
np.random.seed(1234)  # reprodutibilidade
array_aleatorio = np.random.rand(10)

# Ordena o array
array_ordenado = np.sort(array_aleatorio)

print("Array Aleatório:")
print(array_aleatorio)

print("Array Ordenado:")
print(array_ordenado)

Array Aleatório:
[0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]
Array Ordenado:
[0.19151945 0.27259261 0.27646426 0.43772774 0.62210877 0.77997581
 0.78535858 0.80187218 0.87593263 0.95813935]


### Exercícios-005
Considerando 2 `arrays` numpy unidimensionais com 10 valores execute as operações: `np.sum(A)`, `A * B`, `np.inner(A, B)`, `np.outer(A, B)`


e explique o funcionamento de cada operação

In [19]:
import numpy as np

# Define o seed para garantir a reprodutibilidade
np.random.seed(1234)

# Cria dois arrays numpy unidimensionais com 10 valores aleatórios
A = np.random.rand(10)
B = np.random.rand(10)
print("Array A:", A)
print("Array B:", B)

Array A: [0.19151945 0.62210877 0.43772774 0.78535858 0.77997581 0.27259261
 0.27646426 0.80187218 0.95813935 0.87593263]
Array B: [0.35781727 0.50099513 0.68346294 0.71270203 0.37025075 0.56119619
 0.50308317 0.01376845 0.77282662 0.88264119]


In [24]:
# Cálculos requeridos
## Calcula a soma dos elementos de A
soma_A = np.sum(A)

## Multiplicação elemento a elemento de A e B
multiplicacao_elementos = np.multiply(A, B)

## Produto interno de A e B *
produto_interno = np.inner(A, B)

## Produto externo de A e B *
produto_externo = np.outer(A, B)

print("Soma dos elementos de A:", soma_A)

print("Multiplicação elemento a elemento de A e B:")
print(multiplicacao_elementos)

print("Produto interno de A e B:", produto_interno)

print("Produto externo de A e B:") 
print(produto_externo)

Soma dos elementos de A: 6.00169137864497
Multiplicação elemento a elemento de A e B:
[0.06852897 0.31167346 0.29917069 0.55972665 0.28878663 0.15297793
 0.13908451 0.01104054 0.7404756  0.77313422]
Produto interno de A e B: 3.344599203266037
Produto externo de A e B:
[[0.06852897 0.09595031 0.13089645 0.1364963  0.07091022 0.10747999
  0.09635021 0.00263693 0.14801133 0.16904296]
 [0.22260126 0.31167346 0.42518829 0.44337818 0.23033624 0.34912507
  0.31297245 0.00856547 0.48078222 0.54909883]
 [0.15662654 0.21929946 0.29917069 0.31196945 0.16206903 0.24565114
  0.22021346 0.00602683 0.33828765 0.38635653]
 [0.28101486 0.39346082 0.53676348 0.55972665 0.29077961 0.44074024
  0.39510068 0.01081317 0.60694602 0.69318984]
 [0.27908881 0.39076408 0.53308456 0.55589034 0.28878663 0.43771945
  0.3923927  0.01073906 0.60278607 0.68843878]
 [0.09753834 0.13656757 0.18630694 0.1942773  0.10092762 0.15297793
  0.13713675 0.00375318 0.21066682 0.24060146]
 [0.09892369 0.13850724 0.18895307 0.1970

### * Explicações: 
1. Produto interno (ou produto escalar) entre dois vetores é uma operação que resulta em um único número. É calculado multiplicando-se os elementos correspondentes dos vetores e somando esses produtos.

2. Produto Externo (ou produto tensorial) entre dois vetores resulta em uma matriz. Cada elemento da matriz é o produto dos elementos dos vetores.

### Exercícios-006
Crie uma matriz no formato 10x3, extraia linhas com valores diferentes (exemplo: `[2, 2, 3]`):

In [26]:
import numpy as np

np.random.seed(1234)

# Cria uma matriz numpy 10x3 com valores aleatórios inteiros entre 1 e 5
matriz = np.random.randint(1, 6, size=(10, 3))

# Função para verificar se todos os elementos da linha são diferentes
def todos_diferentes(linha):
    return len(np.unique(linha)) == len(linha)
## Compara o número de valores únicos com o comprimento da linha para determinar se todos 
## os valores são diferentes.

# Extrai as linhas com valores diferentes
linhas_diferentes = np.array([linha for linha in matriz if todos_diferentes(linha)])
## cria uma lista de linhas que atendem ao critério de ter valores diferentes entre si 
## e a converte em array numpy

print("Matriz original:")
print(matriz)

print("\nLinhas com valores diferentes:")
print(linhas_diferentes)

Matriz original:
[[4 5 5]
 [1 2 2]
 [2 3 4]
 [5 5 3]
 [3 1 1]
 [5 1 2]
 [3 1 4]
 [5 3 3]
 [4 4 1]
 [2 4 1]]

Linhas com valores diferentes:
[[2 3 4]
 [5 1 2]
 [3 1 4]
 [2 4 1]]


### Exercícios-007
Crie duas matrizes com números aleatórios no formato 2x3, e multiplique a primeira matriz pela transposta da segunda. Explique como o resultado da multiplicação das matrizes foi obtido.

In [27]:
import numpy as np

np.random.seed(1234)

# Cria duas matrizes 2x3 com valores aleatórios inteiros entre 1 e 5
matriz1 = np.random.randint(1, 6, size=(2, 3))
matriz2 = np.random.randint(1, 6, size=(2, 3))

print("Matriz 1:")
print(matriz1)

print("\nMatriz 2:")
print(matriz2)

Matriz 1:
[[4 5 5]
 [1 2 2]]

Matriz 2:
[[2 3 4]
 [5 5 3]]


In [29]:
# Calcula a transposta da segunda matriz, i.e. trocar colunas por linhas
matriz2_transposta = np.transpose(matriz2)

# Multiplica a primeira matriz pela transposta da segunda matriz
resultado = np.dot(matriz1, matriz2_transposta)

print("\nTransposta da Matriz 2:")
print(matriz2_transposta)

print("\nResultado da multiplicação de Matriz 1 pela transposta de Matriz 2:")
print(resultado)


Transposta da Matriz 2:
[[2 5]
 [3 5]
 [4 3]]

Resultado da multiplicação de Matriz 1 pela transposta de Matriz 2:
[[43 60]
 [16 21]]


### Exercício-008

Calcule o percentil de 80% no segundo eixo (_axis_) de uma matriz numpy.

In [30]:
import numpy as np
np.random.seed(1234)

# Cria uma matriz numpy 4x5 com valores aleatórios inteiros entre 1 e 10
matriz = np.random.randint(1, 11, size=(4, 5))

print("Matriz:")
print(matriz)

Matriz:
[[ 4  7  6  5  9]
 [10  2  8 10  7]
 [ 9  1  6  1 10]
 [ 7  3  1  6  3]]


In [32]:
# Calcula o percentil de 80% ao longo do eixo 1 (colunas)
percentil_80 = np.percentile(matriz, 80, axis=1)

print("\nPercentil de 80% ao longo do eixo 1 (colunas):")
print(percentil_80) 

# Explicação do resultado
for i, valor in enumerate(percentil_80):
    print(f"\nPara a linha {i+1}, 80% dos valores estão abaixo de {valor}.")


Percentil de 80% ao longo do eixo 1 (colunas):
[ 7.4 10.   9.2  6.2]

Para a linha 1, 80% dos valores estão abaixo de 7.4.

Para a linha 2, 80% dos valores estão abaixo de 10.0.

Para a linha 3, 80% dos valores estão abaixo de 9.2.

Para a linha 4, 80% dos valores estão abaixo de 6.2.


### Explicações
- O primeiro eixo (axis=0) refere-se às linhas ("y").
- O segundo eixo (axis=1) refere-se às colunas ("x").
- Como o Percentil é Calculado:
- - Para uma linha específica da matriz: (1) Ordena os valores da linha. (2) Encontra o valor que está na posição correspondente ao percentil desejado. Se a posição não for um índice exato, é interpolada entre os valores adjacentes.

### Exercício-009

Crie um programa utilizando pandas para disponibilizar um sumário básico de informações contidas em um _dataframe_:

Informações que devem constar no _dataframe_:

nome - ['Ana', 'Dilma', 'Catarina', 'João', 'Emilia', 'Michel', 'Mateus','Laura', 'Kevin', 'Jonas']

nota - [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19]

tentativas - [1, 3, 2, 3, 2, 3, 1, 1, 2, 1]

qualicacao - ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']

rotulos - ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

In [36]:
import pandas as pd
import numpy as np

# Dados fornecidos
dados = {
    'Nome': ['Ana', 'Dilma', 'Catarina', 'João', 'Emilia', 'Michel', 'Mateus', 'Laura', 'Kevin', 'Jonas'],
    'Nota': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'Tentativas': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'Qualificacao': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'Rotulos': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

In [44]:
# Criação do DataFrame 
df = pd.DataFrame(dados)
df.set_index('Rotulos', inplace=True) # definição da coluna 'rotulos' como índice

df_ord = df.sort_values(by="Nome") # colocar os nomes em ordem alfabética

print("DataFrame:")
print(df_ord)

DataFrame:
             Nome  Nota  Tentativas Qualificacao
Rotulos                                         
a             Ana  12.5           1          yes
c        Catarina  16.5           2          yes
b           Dilma   9.0           3           no
e          Emilia   9.0           2           no
j           Jonas  19.0           1          yes
d            João   NaN           3           no
i           Kevin   8.0           2           no
h           Laura   NaN           1           no
g          Mateus  14.5           1          yes
f          Michel  20.0           3          yes


In [40]:
# Sumário básico de informações
print("\nSumário Básico:")
print(df.describe(include='all'))

# Verificar informações adicionais
print("\nInformações Adicionais:")
print(df.info())


Sumário Básico:
       Nome       Nota  Tentativas Qualificacao Rotulos
count    10   8.000000   10.000000           10      10
unique   10        NaN         NaN            2      10
top     Ana        NaN         NaN          yes       a
freq      1        NaN         NaN            5       1
mean    NaN  13.562500    1.900000          NaN     NaN
std     NaN   4.693746    0.875595          NaN     NaN
min     NaN   8.000000    1.000000          NaN     NaN
25%     NaN   9.000000    1.000000          NaN     NaN
50%     NaN  13.500000    2.000000          NaN     NaN
75%     NaN  17.125000    2.750000          NaN     NaN
max     NaN  20.000000    3.000000          NaN     NaN

Informações Adicionais:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Nome          10 non-null     object 
 1   Nota          8 non-null      float64
 2   Tentativ

### Exercício-010
Escreva num programa para encontras os _n_ menores valores em um _dataframe_ pandas.

In [45]:
import pandas as pd
import numpy as np

# Dados fornecidos
dados = {
    'Nome': ['Ana', 'Dilma', 'Catarina', 'João', 'Emilia', 'Michel', 'Mateus', 'Laura', 'Kevin', 'Jonas'],
    'Nota': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'Tentativas': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'Qualificacao': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes'],
    'Rotulos': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
}

# Criação do DataFrame
df = pd.DataFrame(dados)
df.set_index('Rotulos', inplace=True) # definição da coluna 'rotulos' como índice

df_ord = df.sort_values(by="Nome") # colocar os nomes em ordem alfabética

print(df_ord)

             Nome  Nota  Tentativas Qualificacao
Rotulos                                         
a             Ana  12.5           1          yes
c        Catarina  16.5           2          yes
b           Dilma   9.0           3           no
e          Emilia   9.0           2           no
j           Jonas  19.0           1          yes
d            João   NaN           3           no
i           Kevin   8.0           2           no
h           Laura   NaN           1           no
g          Mateus  14.5           1          yes
f          Michel  20.0           3          yes


In [47]:
while True:
    entrada = input("Digite o número de menores valores que você deseja encontrar: ")
    
    # Verificar se a entrada é um número inteiro
    if entrada.isdigit():
        n = int(entrada)
        
        if n <= 0:
            print("O número de menores valores deve ser maior que zero.")
        else:
            # Encontrar os n menores valores na coluna 'nota'
            menores_notas = df.nsmallest(n, 'Nota')
            
            # Exibir os n menores valores
            print(f"\nOs {n} menores valores na coluna 'Nota':")
            print(menores_notas)
            break  # Sai do loop após exibir os resultados
    else:
        print("Por favor, insira um número inteiro válido.")

Digite o número de menores valores que você deseja encontrar:  -5


Por favor, insira um número inteiro válido.


Digite o número de menores valores que você deseja encontrar:  2.3


Por favor, insira um número inteiro válido.


Digite o número de menores valores que você deseja encontrar:  2



Os 2 menores valores na coluna 'Nota':
          Nome  Nota  Tentativas Qualificacao
Rotulos                                      
i        Kevin   8.0           2           no
b        Dilma   9.0           3           no


### Exercício-011
Escreva um programa para encontrar dentro de um intervalo fixado (exemplo: $a<x<b$) e substituí-los por 0.

In [48]:
import pandas as pd
import numpy as np

np.random.seed(1234)

# Criar um DataFrame com valores aleatórios
df = pd.DataFrame({
    'A': np.random.randint(1, 20, size=10),
    'B': np.random.randint(1, 20, size=10),
    'C': np.random.randint(1, 20, size=10)
})

print("DataFrame original:")
print(df)

DataFrame original:
    A   B   C
0  16  17   8
1   7  10  12
2  13  16   1
3  16  19  10
4  18  17  12
5  10  13  17
6  12   6   4
7  13   3   3
8  17   7  13
9   6   4   2


In [49]:
# Definir o intervalo
a = 5
b = 15

In [52]:
# Converter DataFrame para um array NumPy
df_array = df.to_numpy()

# Substituir valores no intervalo (a < x < b) por 0 usando operações vetorizadas do NumPy
df_array[(df_array > a) & (df_array < b)] = 0

# Converter o array de volta para DataFrame
df = pd.DataFrame(df_array, columns=df.columns)

print("\nDataFrame após substituição:")
print(df)


DataFrame após substituição:
    A   B   C
0  16  17   0
1   0   0   0
2   0  16   1
3  16  19   0
4  18  17   0
5   0   0  17
6   0   0   4
7   0   3   3
8  17   0   0
9   0   4   2


### Exercício-012
Utilize os métodos `max` para encontrar o máximo de uma coluna em _dataframe_ pandas e depois `query` para encontrar onde os valores na coluna referida são menores que o máximo.

In [53]:
import pandas as pd
import numpy as np

np.random.seed(1234)

# Criar um DataFrame com valores aleatórios
df = pd.DataFrame({
    'A': np.random.randint(1, 20, size=10),
    'B': np.random.randint(1, 20, size=10),
    'C': np.random.randint(1, 20, size=10)
})

print("DataFrame original:")
print(df)

DataFrame original:
    A   B   C
0  16  17   8
1   7  10  12
2  13  16   1
3  16  19  10
4  18  17  12
5  10  13  17
6  12   6   4
7  13   3   3
8  17   7  13
9   6   4   2


In [54]:
# Encontrar o valor máximo na coluna 'A'
max_val = df['A'].max()

print(f"\nValor máximo na coluna 'A': {max_val}")


Valor máximo na coluna 'A': 18


In [55]:
# Usar query para encontrar onde os valores na coluna 'A' são menores que o valor máximo
df_filtered = df.query('A < @max_val')

print("\nDataFrame onde os valores na coluna 'A' são menores que o valor máximo:")
print(df_filtered)


DataFrame onde os valores na coluna 'A' são menores que o valor máximo:
    A   B   C
0  16  17   8
1   7  10  12
2  13  16   1
3  16  19  10
5  10  13  17
6  12   6   4
7  13   3   3
8  17   7  13
9   6   4   2


In [56]:
# Encontrar as linhas removidas
df_removed = df[~df.index.isin(df_filtered.index)]

print("\nLinhas removidas:")
print(df_removed)


Linhas removidas:
    A   B   C
4  18  17  12


### Exercício-013
Remova os espaços na extremidade dos nomes das colunas e transforme em minúsculo utilizando o método `.str` para o conjunto de dados listado abaixo.

In [57]:
import pandas as pd

df = pd.DataFrame({
    'Nome': ['Alberto Franco','Giovane Pereira','Reinaldo Oliveira', 'Elen Cavalcanti', 'Paulo Freire'],
    'Data_de_Nascimento ': ['17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'Idade': [18.5, 21.2, 22.5, 22, 23]
})

print("DataFrame original:")
print(df)

DataFrame original:
                Nome Data_de_Nascimento   Idade
0     Alberto Franco          17/05/2002   18.5
1    Giovane Pereira          16/02/1999   21.2
2  Reinaldo Oliveira          25/09/1998   22.5
3    Elen Cavalcanti          11/05/2002   22.0
4       Paulo Freire          15/09/1997   23.0


In [58]:
# Ajustar os nomes das colunas
df.columns = df.columns.str.strip().str.lower() # obs. further check str - interesting to fix stuff 

print("\nDataFrame com nomes de colunas ajustados:")
print(df)


DataFrame com nomes de colunas ajustados:
                nome data_de_nascimento  idade
0     Alberto Franco         17/05/2002   18.5
1    Giovane Pereira         16/02/1999   21.2
2  Reinaldo Oliveira         25/09/1998   22.5
3    Elen Cavalcanti         11/05/2002   22.0
4       Paulo Freire         15/09/1997   23.0


### Exercício-014
Preencha os dados de um _dataframe_ nas posições em que os dados são nulos com um segundo _dataframe_ para o conjunto de dados listado abaixo.

In [2]:
import pandas as pd

# Criar o primeiro DataFrame com valores nulos
df1 = pd.DataFrame({'A': [None, 0, None], 'B': [3, 4, 5]})

# Criar o segundo DataFrame com valores para preencher os nulos
df2 = pd.DataFrame({'A': [1, 1, 3], 'B': [3, None, 3]})

print("DataFrame 1 com valores nulos:")
print(df1)

print("\nDataFrame 2 com valores para preencher:")
print(df2)

DataFrame 1 com valores nulos:
     A  B
0  NaN  3
1  0.0  4
2  NaN  5

DataFrame 2 com valores para preencher:
   A    B
0  1  3.0
1  1  NaN
2  3  3.0


In [60]:
# Preencher valores nulos em df1 com valores de df2
df1_filled = df1.fillna(df2)

print("\nDataFrame 1 após preenchimento dos valores nulos:")
print(df1_filled)


DataFrame 1 após preenchimento dos valores nulos:
     A  B
0  1.0  3
1  0.0  4
2  3.0  5


### Exercício-015
Escreva um programa que primeiro concatena dois _dataframe_ e depois faz operação de união (`merge`) com um terceiro em uma coluna especificada para o conjunto de dados listado abaixo.

In [67]:
import pandas as pd

# Dados fornecidos
dados_estudante1 = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5'],
         'name': ['Daniela', 'Riobaldo', 'Bruno', 'Eduardo', 'Monica'],
        'notas': [200, 210, 190, 222, 199]})

dados_estudante2 = pd.DataFrame({
        'codigo': ['S4', 'S5', 'S6', 'S7', 'S8'],
        'name': ['Isabela', 'Carla', 'Denise', 'Carmen', 'Madalena'],
        'notas': [201, 200, 198, 219, 201]})

exam_data = pd.DataFrame({
        'codigo': ['S1', 'S2', 'S3', 'S4', 'S5', 'S7', 'S8', 'S9', 'S10', 'S11', 'S12', 'S13'],
        'id_prova': [23, 45, 12, 67, 21, 55, 33, 14, 56, 83, 88, 12]})

In [68]:
print("Dados Estudante 1:")
print(dados_estudante1)

print("\nDados Estudante 2:")
print(dados_estudante2)

print("\nDados de Exames:")
print(exam_data)

Dados Estudante 1:
  codigo      name  notas
0     S1   Daniela    200
1     S2  Riobaldo    210
2     S3     Bruno    190
3     S4   Eduardo    222
4     S5    Monica    199

Dados Estudante 2:
  codigo      name  notas
0     S4   Isabela    201
1     S5     Carla    200
2     S6    Denise    198
3     S7    Carmen    219
4     S8  Madalena    201

Dados de Exames:
   codigo  id_prova
0      S1        23
1      S2        45
2      S3        12
3      S4        67
4      S5        21
5      S7        55
6      S8        33
7      S9        14
8     S10        56
9     S11        83
10    S12        88
11    S13        12


In [69]:
# Concatenar dados_estudante1 e dados_estudante2
dados_concatenados = pd.concat([dados_estudante1, dados_estudante2], ignore_index=True)

print("\nDados Estudantes Concatenados:")
print(dados_concatenados)


Dados Estudantes Concatenados:
  codigo      name  notas
0     S1   Daniela    200
1     S2  Riobaldo    210
2     S3     Bruno    190
3     S4   Eduardo    222
4     S5    Monica    199
5     S4   Isabela    201
6     S5     Carla    200
7     S6    Denise    198
8     S7    Carmen    219
9     S8  Madalena    201


In [70]:
# Realizar a união (merge) com exam_data baseado na coluna 'codigo'
dados_unidos = pd.merge(dados_concatenados, exam_data, on='codigo', how='left')

print("\nDados Estudantes e Exames Unidos:")
print(dados_unidos)


Dados Estudantes e Exames Unidos:
  codigo      name  notas  id_prova
0     S1   Daniela    200      23.0
1     S2  Riobaldo    210      45.0
2     S3     Bruno    190      12.0
3     S4   Eduardo    222      67.0
4     S5    Monica    199      21.0
5     S4   Isabela    201      67.0
6     S5     Carla    200      21.0
7     S6    Denise    198       NaN
8     S7    Carmen    219      55.0
9     S8  Madalena    201      33.0


### Exercício-016
Escreva um programa que faz operação de união (`merge`) utilizando mais de uma coluna para o conjunto de dados listado abaixo.

In [72]:
import pandas as pd
data1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'P': ['P0', 'P1', 'P2', 'P3'],
                     'Q': ['Q0', 'Q1', 'Q2', 'Q3']})
data2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'R': ['R0', 'R1', 'R2', 'R3'],
                      'S': ['S0', 'S1', 'S2', 'S3']})

In [73]:
print("Data1:")
print(data1)

print("\nData2:")
print(data2)

Data1:
  key1 key2   P   Q
0   K0   K0  P0  Q0
1   K0   K1  P1  Q1
2   K1   K0  P2  Q2
3   K2   K1  P3  Q3

Data2:
  key1 key2   R   S
0   K0   K0  R0  S0
1   K1   K0  R1  S1
2   K1   K0  R2  S2
3   K2   K0  R3  S3


In [74]:
# Realizar a união (merge) com base nas colunas 'key1' e 'key2'
merged_data = pd.merge(data1, data2, on=['key1', 'key2'], how='inner')

print("\nData após a união (merge):")
print(merged_data)


Data após a união (merge):
  key1 key2   P   Q   R   S
0   K0   K0  P0  Q0  R0  S0
1   K1   K0  P2  Q2  R1  S1
2   K1   K0  P2  Q2  R2  S2
